config/routes.rb
Rails.application.routes.draw do
  resources :commits, only: :index
  resources :users, only: :update
  resources :import_commits, only:[:new, :create]
  root to: 'import_commits#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commit.rb
class Commit < ApplicationRecord
  belongs_to :user
end

app/models/import_commit.rb
class ImportCommit 
  attr_reader :username, :repository

  def initialize(username, repository)
    @username = username
    @repository = repository
  end

  def import_commits!
    clear_commits!
    begin
      data = data_from
    rescue StandardError => e
      case e.response.code
        when 404
          raise 'Wrong Name or Repository'
        when 403
          raise 'limit is Exceeded'
      end
    end
    create_data(data)
  end

  private
  def data_from
    n = 1; result = []
    while (request = JSON.parse(RestClient.get "https://api.github.com/repos/#{username}/#{repository}/commits?page=#{n}")).any?
      result += request
      n = n.next
    end
    result
  end

  def create_data(result)
    result.map! do |record|
      user = define_user_by(record)
      create_commit_for!(user, record)
    end
  end

  def define_user_by(record)
    User.find_or_create_by(email: record['commit']['author']['email']) do |user|
      user.name = record['commit']['author']['name']
    end
  end

  def create_commit_for!(user, record)
    user.commits.create(
      sha_hash: record['sha'],
      date: record['commit']['author']['date'],
      description: record['commit']['message']
    )
  end

  def clear_commits!
    User.destroy_all
  end 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :commits, dependent: :destroy
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  include Pagy::Backend

  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  before_action :set_user

  def index
    @pagy, @commits = pagy((@user ? @user.commits : Commit).order(:date), items: 10)
    respond_with(@commits)
  end

  private

  def set_user
    @user = User.find_by(email: params[:email]) if params[:email]
  end
end

app/controllers/import_commits_controller.rb
class ImportCommitsController < ApplicationController
  def new; end

  def create
    respond_with(get_commits) do |format|
      format.html { redirect_to commits_path }
    end
  rescue StandardError => e
    flash[:alert] = e.message
    render :new
  end

  private

  def get_commits
    ImportCommit.new(params[:user_name], params[:repository]).import_commits!
  end

  def interpolation_options
    { resource_name: 'Request' }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  respond_to :json

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/helpers/import_commits_helper.rb
module ImportCommitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/commits/_search.html.erb
<%= form_tag commits_path, method: :get do %>

  <div class="input-field">
    <input id="search" type="search" required>
    <label class="label-icon" for="search"><i class="material-icons">search</i></label>
    <i class="material-icons">close</i>
  </div>
<% end %>

app/views/commits/index.html.erb
<table>
  <thead>
    <tr>
        <th>Date</th>
        <th>Name</th>
        <th>Email</th>
        <th>Sha_hash</th>
        <th>Desription</th>
    </tr>
  </thead>

  <tbody>
    <% @commits.each do |commit| %>
      <tr>
        <td><%= commit.date.to_time.to_formatted_s(:long) %></td>  
        <td><%= commit.user.name %></td>
        <td><%= commit.user.email %></td>
        <td><%= commit.sha_hash %></td>
        <td><%= commit.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%== pagy_materialize_nav(@pagy) %>

app/views/common/_errors.html.erb
<% resource.errors.full_messages.each do |message| %> 
  <%= message %>
<% end %>

app/views/import_commits/new.html.erb
<div class="row">
  <%= form_tag import_commits_path, method: :post, class: "col s12" do %>
    <div class="row">
      <div class="input-field col s12">
        <%= text_field_tag :user_name, '', class: 'validate', required: "required", placeholder: 'Username' %>
      </div>

      <div class="input-field col s12">
        <%= text_field_tag :repository, '', class: 'validate', required: "required", placeholder: 'Repository' %>
      </div>

      <button class="btn waves-effect waves-light" type="submit" name="action"><%= submit_tag 'Import commits' %>
        <i class="material-icons right">send</i>
      </button>
    </div>
  <% end %>
</div>


<% if notice %>
  <script type="text/javascript">
    Materialize.toast('<%= notice %>', 4000)
  </script>
<% end %>
<% if alert %>
  <script type="text/javascript">
    Materialize.toast('<%= alert %>', 4000)
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Health24</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <% if controller_name == 'commits' %>
          <%= render 'commits/search' %>
        <% else %>
          <%= link_to "Health24", root_path, class: "brand-logo right" %>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <% if flash.any? %>
        <div class="content-wrapper buffer-both">
          <% flash.each do |name, message| %>
            <ul class="collection">
              <li class="collection-item">
                <%= content_tag :div, message, class: "flash-#{name}" %>
              </li>
            </ul>
          <% end %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>